### ISSUE TITLE
Make photos in individual Collections (Stories) page the same width as the text column

### ISSUE THREAD

**Issue by anexasajoop** [twozeroone/tikola#19]

**Comment by prtksxna** [comment]
Cool so, I'll explain, when you add an image using the wordpress editor it adds a lot of cruft code. At this point I don't know how to stop that and sid isn't around to explain this to me. So we'll do a kind of work around to fix this. 

If you go to http://isl.prtksxna.com/wp-admin/post.php?post=40&action=edit and switch to "Text" instead of "Visual". You'll see that the code for the image is:

```
[caption id="attachment_25" align="alignnone" width="300"]<img class="size-medium wp-image-25" src="http://isl.prtksxna.com/wp-content/uploads/2017/11/SukhadiaCircle4-300x300.jpg" alt="" width="300" height="300" /> Charbhuja Juice[/caption]
```

The `caption` and `widths` there are not needed. You have to change it to something like this:

```
<img class="wp-image-29 size-full" src="http://isl.prtksxna.com/wp-content/uploads/2017/11/SukhadiaCircle5.jpg" alt=""/>
```

***

Also when adding images right now you've chosen a 300px width, so you'll have to remove the images you have right now, and add them again on full size:

![screen shot 2017-11-12 at 1 23 47 pm](https://user-images.githubusercontent.com/9491/32697040-db580596-c7ac-11e7-9d35-1a1820b6802d.png)
